# Generated by Django 3.0.11 on 2021-02-06 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('venue', models.CharField(max_length=50)),
                ('sig', models.CharField(max_length=20, null=True)),
                ('mentors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
